### ISSUE TITLE
After wake from sleep, display manager for RGB LED is stuck

### ISSUE THREAD

**Issue by jbobrow** [jbobrow/Move38-blinks-firmware#5]
To recreate, use example for fadeTo or fadeToCycle and test. Works just fine until Blink goes to sleep and wakes up. Then Blink is stuck without the ability to animate.

**Comment by LasVegasOle** [comment]
I have pushed this change to master directly, not on purpose (sorry), not sure where the issue is, I have uncommented all the code from old library and it works. But whenever I try to delete some parts that should not be related it fails, that includes, transmitting code from the main and microphone ISR. The problem is that the size of the whole code went up to 7.3k.

**Comment by bigjosh** [comment]
Want me to take a look? If so, which commit introduces the issue?

**Comment by LasVegasOle** [comment]
Thanks! Would be nice if you could test if its working now. The problem is that, I commented a lot of code from the original library to reduce the size, but everything seems to be really interconnected, so after uncommenting it, it worked again but turn out to be really big.

**Comment by jbobrow** [comment]
Working now, as for the commenting out of code. Not worth chasing.
